[[post]]
category = "Tech"
title = "Using Deepfake Realtime Live Streaming"
subtitle = "How to Live using Deepfake Using Realtime Camera."
datetime = "2024-08-12"
image = "https://docs.arn.my.id/content/images/size/w2000/2024/08/demo1.png"
url = "https://docs.arn.my.id/how-to-live-using-deepfake-using-realtime-camera/"

[[post]]
category = "Design"
title = "Best fonts every designer"
subtitle = "Sed ut perspiciatis, nam libero tempore, cum soluta nobis est eligendi"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-2.jpg"
url = "https://dev.to"

[[post]]
category = "Design"
title = "Design digest #80"
subtitle = "Excepteur sint occaecat cupidatat no proident, quis nostrum exercitationem ullam corporis suscipit"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-3.jpg"
url = "https://hashnode.com"

[[post]]
category = "Design"
title = "UI interactions of the week"
subtitle = "Enim ad minim veniam, consectetur adipiscing elit, quis nostrud exercitation ullamco laboris nisi"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-4.jpg"
url = "https://dev.to"

[[post]]
category = "Design"
title = "The Forgotten Art Of Spacing"
subtitle = "Maxime placeat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-5.jpg"
url = "https://medium.com"

[[post]]
category = "Design"
title = "Design Digest #79"
subtitle = "Optio cumque nihil impedit uo minus quod maxime placeat, velit esse cillum"
datetime = "2022-02-23"
image = "./config/assets/posts/blog-6.jpg"
url = "https://hashnode.com"
