############## Education config #################
#################################################
[[education]]
title = "High School"
timeline = "2009 — 2012"
description = "Duis aute irure dolor in reprehenderit in voluptate, quila voluptas mag odit aut fugit, sed consequuntur magni dolores eos."

[[education]]
title = "Yogyakarta Muhammadiyah University"
timeline = "2015 — 2019"
description = "Management of Economic and Bussines"

[[education]]
title = "Terbuka University"
timeline = "2022 — Now"
description = "Law"


############## Experience config ################
#################################################
[[experience]]
title = "Web designer"
timeline = "2010 — 2013"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Art director"
timeline = "2013 — 2015"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Creative director"
timeline = "2015 — Present"
description = "Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Puclic"
value = "80%"

[[skill]]
title = "Excel"
value = "70%"

[[skill]]
title = "Words"
value = "90%"

[[skill]]
title = "Managing"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Bahasa Indonesia"
value = "90%"

[[language]]
title = "English"
value = "70%"
